name: CI workflow

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v7

      - name: Bootstrap the build system
        run: autoreconf --install --force

      - name: Configure
        run: ./configure

      - name: Build
        run: make

      - name: Run Distcheck
        run: make distcheck
